# Generated by Django 2.0.3 on 2018-04-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180404_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Invitees',
        ),
    ]
