# Generated by Django 2.0.4 on 2018-05-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_invitees_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitees',
            name='name',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
